//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 写轴器.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("写轴器.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;170101&quot;: [ 1, 1, 1, 2 ]
        ///} 的本地化字符串。
        /// </summary>
        internal static string UB {
            get {
                return ResourceManager.GetString("UB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///  &quot;天狼噬斩&quot;,
        ///  &quot;斩刃风暴&quot;,
        ///  &quot;乱数圣域&quot;,
        ///  &quot;闪耀之刃&quot;,
        ///  &quot;演出开始&quot;,
        ///  &quot;琉球犬重拳出击&quot;,
        ///  &quot;箭贯汝身！&quot;,
        ///  &quot;日和莉突击&quot;,
        ///  &quot;把你变成布丁&quot;,
        ///  &quot;英雄虎爆弹&quot;,
        ///  &quot;捣蛋炸弹&quot;,
        ///  &quot;惊吓挥铃&quot;,
        ///  &quot;噗吉全力挥动&quot;,
        ///  &quot;神魂颠倒&quot;,
        ///  &quot;高贵突击&quot;,
        ///  &quot;猫猫决胜爪&quot;,
        ///  &quot;致命打击&quot;,
        ///  &quot;御久间流奥义·阿修罗&quot;,
        ///  &quot;毛茸茸挥击&quot;,
        ///  &quot;炼狱火海之盾&quot;,
        ///  &quot;零之太刀·水月镜花&quot;,
        ///  &quot;神圣惩击&quot;,
        ///  &quot;致死束缚&quot;,
        ///  &quot;公主突袭&quot;,
        ///  &quot;天楼霸断剑&quot;,
        ///  &quot;公主飞溅&quot;,
        ///  &quot;疾风剑雨&quot;,
        ///  &quot;细冰剑·雪华&quot;,
        ///  &quot;日和莉快乐印章&quot;,
        ///  &quot;噗吉圣诞·风暴&quot;,
        ///  &quot;猫猫夏日狂欢&quot;,
        ///  &quot;冬季的铃声&quot;,
        ///  &quot;爱的惩罚&quot;,
        ///  &quot;兔兔斩击&quot;,
        ///  &quot;尝尝亲手烘培的红豆包&quot;,
        ///  &quot;甜蜜恶魔声援&quot;,
        ///  &quot;闪电标枪&quot;,
        ///  &quot;罗刹涅槃·极光终天冥坏破&quot;,
        ///  &quot;亡灵恐惧&quot;,
        ///  &quot;来吧！伊丽莎白&quot;,
        ///  &quot;七重纱护&quot;,
        ///  &quot;凤凰之剑&quot;,
        ///  &quot;忍法灼烧地域&quot;,
        ///  &quot;紫电一闪&quot;,
        ///  &quot;飞跃枪闪&quot;,
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UBNameDic {
            get {
                return ResourceManager.GetString("UBNameDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;真琴&quot;: &quot;狼&quot;,
        ///  &quot;克莉丝提娜&quot;: &quot;克&quot;,
        ///  &quot;怜&quot;: &quot;剑圣&quot;,
        ///  &quot;香织&quot;: &quot;狗&quot;,
        ///  &quot;日和莉&quot;: &quot;猫拳&quot;,
        ///  &quot;宫子&quot;: &quot;布丁&quot;,
        ///  &quot;茉莉&quot;: &quot;茉莉&quot;,
        ///  &quot;未奏希&quot;: &quot;炸弹人&quot;,
        ///  &quot;绫音&quot;: &quot;熊锤&quot;,
        ///  &quot;空花&quot;: &quot;空花&quot;,
        ///  &quot;秋乃&quot;: &quot;哈哈剑&quot;,
        ///  &quot;珠希&quot;: &quot;猫剑&quot;,
        ///  &quot;智&quot;: &quot;智&quot;,
        ///  &quot;惠里子&quot;: &quot;病娇&quot;,
        ///  &quot;流夏&quot;: &quot;流夏&quot;,
        ///  &quot;静流&quot;: &quot;姐姐&quot;,
        ///  &quot;佩可莉姆（夏日）&quot;: &quot;水吃&quot;,
        ///  &quot;珠希（夏日）&quot;: &quot;水猫&quot;,
        ///  &quot;莉玛&quot;: &quot;羊驼&quot;,
        ///  &quot;纯&quot;: &quot;黑骑&quot;,
        ///  &quot;纺希&quot;: &quot;裁缝&quot;,
        ///  &quot;佩可莉姆&quot;: &quot;佩可&quot;,
        ///  &quot;姬塔&quot;: &quot;姬塔&quot;,
        ///  &quot;胡桃（圣诞节）&quot;: &quot;圣铃&quot;,
        ///  &quot;环奈（振袖）&quot;: &quot;春环&quot;,
        ///  &quot;アヤネ（クリスマス）&quot;: &quot;圣锤&quot;,
        ///  &quot;凌音（圣诞节）&quot;: &quot;圣锤&quot;,
        ///  &quot;可可萝（夏日）&quot;: &quot;水白&quot;,
        ///  &quot;ヒヨリ（ニューイヤー）&quot;: ... 的本地化字符串。
        /// </summary>
        internal static string UnitNameDic {
            get {
                return ResourceManager.GetString("UnitNameDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 轴模板 {
            get {
                object obj = ResourceManager.GetObject("轴模板", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
